root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main.exe cmd/main.go"
  bin = "tmp/main.exe"
  delay = 1000
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[run]
  cmd = "cmd /c tmp\\main.exe"

[log]
  time = true

[misc]
  clean_on_exit = true
